import fs from "fs";
import path from "path";
import puppeteer from "puppeteer";

function currency(value) {
  return `$${Number(value || 0).toFixed(2)}`;
}

export function renderPayslipHtml(record) {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Payslip ${record.staff_name}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #172033; margin: 40px; }
    .header { border-bottom: 3px solid #1b7f79; padding-bottom: 16px; margin-bottom: 24px; }
    h1 { margin: 0; font-size: 28px; }
    h2 { margin: 6px 0 0; color: #526071; font-size: 16px; font-weight: 500; }
    table { width: 100%; border-collapse: collapse; margin-top: 18px; }
    th, td { text-align: left; border-bottom: 1px solid #d8dee9; padding: 10px; }
    th { background: #eef7f6; }
    .total { font-weight: 700; }
    .net { color: #0f766e; font-size: 20px; }
    .notes { margin-top: 24px; padding: 14px; background: #f6f8fb; border-radius: 8px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>PayNivo Pte Ltd</h1>
    <h2>Payslip for ${record.payroll_month}</h2>
  </div>
  <p><strong>Staff:</strong> ${record.staff_name} (${record.staff_id})</p>
  <p><strong>Work location:</strong> ${record.work_location || "Singapore HQ"}</p>
  <p><strong>Working days:</strong> ${record.working_days} | <strong>No pay leave:</strong> ${record.no_pay_leave_days}</p>
  <table>
    <tr><th>Earnings</th><th>Amount</th></tr>
    <tr><td>Basic salary</td><td>${currency(record.basic_salary)}</td></tr>
    <tr><td>Services commission</td><td>${currency(record.services_commission)}</td></tr>
    <tr><td>Product commission</td><td>${currency(record.product_commission)}</td></tr>
    <tr><td>Credit commission</td><td>${currency(record.credit_commission)}</td></tr>
    <tr><td>Allowance</td><td>${currency(record.allowance)}</td></tr>
    <tr class="total"><td>Total earnings</td><td>${currency(record.total_earnings)}</td></tr>
  </table>
  <table>
    <tr><th>Deductions</th><th>Amount</th></tr>
    <tr><td>CPF deduction</td><td>${currency(record.employee_cpf)}</td></tr>
    <tr><td>Loan deduction</td><td>${currency(record.loan_deduction)}</td></tr>
    <tr><td>Other deduction</td><td>${currency(record.other_deduction)}</td></tr>
    <tr class="total"><td>Total deductions</td><td>${currency(record.total_deductions)}</td></tr>
  </table>
  <p class="net"><strong>Net pay:</strong> ${currency(record.net_pay)}</p>
  <div class="notes"><strong>Notes:</strong> Prototype payslip generated by PayNivo. Values are for FYP demonstration.</div>
</body>
</html>`;
}

export async function generatePayslipPdf(record, outputDir) {
  fs.mkdirSync(outputDir, { recursive: true });
  const filename = `payslip-${record.staff_id}-${String(record.payroll_month).replace(/\s+/g, "-")}.pdf`;
  const filePath = path.join(outputDir, filename);
  const browser = await puppeteer.launch({
    headless: true,
    timeout: 60000,
    protocolTimeout: 60000,
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
  });
  const page = await browser.newPage();
  await page.setContent(renderPayslipHtml(record), { waitUntil: "networkidle0" });
  await page.pdf({ path: filePath, format: "A4", printBackground: true });
  await browser.close();
  return { filename, filePath };
}
