import payNivoReportLogo from "../assets/paynivo-logo-report-dark.jpg?inline";

const COLORS = {
  charcoal: "0.12 0.12 0.12",
  coral: "0.95 0.35 0.31",
  ink: "0.10 0.10 0.12",
  muted: "0.38 0.40 0.44",
  border: "0.82 0.83 0.85",
  soft: "0.96 0.96 0.96",
  white: "1 1 1"
};

const PAYNIVO_LOGO_HEX = Array.from(atob(payNivoReportLogo.split(",")[1] || ""), (character) =>
  character.charCodeAt(0).toString(16).padStart(2, "0")
).join("");

function cleanText(value) {
  return String(value ?? "")
    .replaceAll("\\", "\\\\")
    .replaceAll("(", "\\(")
    .replaceAll(")", "\\)")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[^\x20-\x7e]/g, "?");
}

function wrapText(value, maxCharacters) {
  const paragraphs = String(value ?? "").split(/\r?\n/);
  const lines = [];

  paragraphs.forEach((paragraph) => {
    const words = paragraph.split(/\s+/).filter(Boolean);
    let current = "";

    words.forEach((word) => {
      const pieces = word.length > maxCharacters
        ? word.match(new RegExp(`.{1,${maxCharacters}}`, "g")) || [word]
        : [word];

      pieces.forEach((piece) => {
        const next = current ? `${current} ${piece}` : piece;
        if (next.length > maxCharacters && current) {
          lines.push(current);
          current = piece;
        } else {
          current = next;
        }
      });
    });

    lines.push(current);
  });

  return lines.length ? lines : [""];
}

function columnWeights(columnCount) {
  const presets = {
    1: [1],
    2: [0.42, 0.58],
    3: [0.27, 0.27, 0.46],
    4: [0.20, 0.29, 0.25, 0.26],
    5: [0.19, 0.22, 0.20, 0.19, 0.20],
    6: [0.18, 0.16, 0.17, 0.16, 0.16, 0.17],
    7: [0.17, 0.14, 0.16, 0.13, 0.13, 0.14, 0.13]
  };
  return presets[columnCount] || Array(columnCount).fill(1 / columnCount);
}

function formatGeneratedAt(value) {
  const date = value instanceof Date ? value : new Date(value || Date.now());
  return new Intl.DateTimeFormat("en-SG", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(date);
}

export function buildPayrollReportPdf({
  category = "PAYROLL REPORTING",
  categorySubtitle = "Controlled payroll record and management report",
  footer = "Generated by the Automated Payroll System.",
  generatedAt = new Date(),
  orientation = "auto",
  subtitle = "",
  summaryRows = [],
  tableRows = [],
  title = "Payroll Report"
} = {}) {
  const normalizedTable = tableRows.map((row) => Array.from(row || [], (cell) => String(cell ?? "")));
  const headers = normalizedTable[0] || [];
  const rows = normalizedTable.slice(1);
  const landscape = orientation === "landscape" || (orientation === "auto" && headers.length >= 6);
  const page = landscape
    ? { width: 842, height: 595, margin: 36 }
    : { width: 595, height: 842, margin: 42 };
  const bottom = 58;
  const pages = [];
  let commands;
  let y;
  let tableState = null;

  const rect = (x, rectY, width, height, color) => {
    commands.push("q", `${color} rg`, `${x.toFixed(2)} ${rectY.toFixed(2)} ${width.toFixed(2)} ${height.toFixed(2)} re`, "f", "Q");
  };
  const line = (x1, y1, x2, y2, color = COLORS.border, width = 0.7) => {
    commands.push("q", `${color} RG`, `${width} w`, `${x1.toFixed(2)} ${y1.toFixed(2)} m`, `${x2.toFixed(2)} ${y2.toFixed(2)} l`, "S", "Q");
  };
  const text = (value, x, textY, size = 8, color = COLORS.ink, font = "F1") => {
    commands.push("BT", `${color} rg`, `/${font} ${size} Tf`, `${x.toFixed(2)} ${textY.toFixed(2)} Td`, `(${cleanText(value)}) Tj`, "ET");
  };
  const logo = (x, logoY, size) => {
    commands.push("q", `${size} 0 0 ${size} ${x.toFixed(2)} ${logoY.toFixed(2)} cm`, "/Logo Do", "Q");
  };

  const addPage = (continuation = false) => {
    commands = [];
    pages.push(commands);
    rect(0, 0, page.width, page.height, COLORS.white);
    rect(0, page.height - 82, page.width, 82, COLORS.charcoal);
    rect(0, page.height - 86, page.width, 4, COLORS.coral);
    text(category.toUpperCase(), page.margin, page.height - 34, 10, COLORS.white, "F2");
    text(categorySubtitle, page.margin, page.height - 51, 8, "0.78 0.78 0.78");
    logo(page.width - page.margin - 66, page.height - 78, 64);
    line(page.margin, 38, page.width - page.margin, 38, "0.75 0.75 0.75", 0.6);
    text(footer, page.margin, 23, 7, COLORS.muted);
    text(`Page ${pages.length} of {{PAGE_COUNT}}`, page.width - page.margin - 72, 23, 7, COLORS.muted);

    y = page.height - 122;
    text(continuation ? `${title} - Continued` : title.toUpperCase(), page.margin, y, continuation ? 16 : 22, COLORS.ink, "F2");
    y -= continuation ? 27 : 25;
    if (!continuation && subtitle) {
      text(subtitle, page.margin, y, 9, COLORS.muted);
      y -= 22;
    }
    if (continuation) y -= 3;
  };

  const ensureSpace = (height, continuation = true) => {
    if (y - height >= bottom) return false;
    addPage(continuation);
    return true;
  };

  const drawTableHeader = () => {
    if (!headers.length) return;
    const tableWidth = page.width - page.margin * 2;
    const weights = columnWeights(headers.length);
    const widths = weights.map((weight) => tableWidth * weight);
    const xs = widths.reduce((positions, width) => [...positions, positions.at(-1) + width], [page.margin]);
    const headerLines = headers.map((header, index) => wrapText(header, Math.max(6, Math.floor((widths[index] - 12) / 4.2))));
    const headerHeight = Math.max(25, Math.max(...headerLines.map((lines) => lines.length)) * 8 + 10);
    rect(page.margin, y - headerHeight, tableWidth, headerHeight, COLORS.charcoal);
    headerLines.forEach((cellLines, columnIndex) => {
      cellLines.forEach((cellLine, lineIndex) => {
        text(cellLine, xs[columnIndex] + 6, y - 12 - lineIndex * 8, 6.5, COLORS.white, "F2");
      });
    });
    y -= headerHeight;
    tableState = { tableWidth, widths, xs };
  };

  addPage(false);
  text(`Generated ${formatGeneratedAt(generatedAt)}`, page.margin, y, 7.5, COLORS.muted);
  y -= 22;

  if (summaryRows.length) {
    text("REPORT OVERVIEW", page.margin, y, 11, COLORS.ink, "F2");
    y -= 14;
    const gap = 10;
    const cardWidth = (page.width - page.margin * 2 - gap) / 2;

    summaryRows.forEach((summary, index) => {
      if (index % 2 === 0) ensureSpace(48);
      const x = page.margin + (index % 2) * (cardWidth + gap);
      rect(x, y - 40, cardWidth, 40, COLORS.soft);
      rect(x, y - 40, 3, 40, COLORS.coral);
      text(summary[0] || "", x + 11, y - 13, 7, COLORS.muted, "F2");
      text(summary[1] || "", x + 11, y - 28, 9, COLORS.ink, "F2");
      if (summary[2]) text(summary[2], x + cardWidth * 0.58, y - 28, 7, COLORS.muted);
      if (index % 2 === 1 || index === summaryRows.length - 1) y -= 48;
    });
    y -= 7;
  }

  if (headers.length) {
    ensureSpace(65);
    text("REPORT DETAILS", page.margin, y, 11, COLORS.ink, "F2");
    y -= 14;
    drawTableHeader();

    rows.forEach((row, rowIndex) => {
      const wrapped = headers.map((_, columnIndex) => {
        const width = tableState.widths[columnIndex];
        return wrapText(row[columnIndex] ?? "", Math.max(5, Math.floor((width - 12) / 3.9)));
      });
      let lineOffset = 0;
      const totalLines = Math.max(1, ...wrapped.map((cell) => cell.length));

      while (lineOffset < totalLines) {
        const availableLines = Math.floor((y - bottom - 10) / 9);
        if (availableLines < 1) {
          addPage(true);
          drawTableHeader();
          continue;
        }

        const fragmentLines = Math.min(totalLines - lineOffset, availableLines);
        const rowHeight = Math.max(24, fragmentLines * 9 + 10);
        rect(page.margin, y - rowHeight, tableState.tableWidth, rowHeight, rowIndex % 2 ? COLORS.soft : COLORS.white);
        line(page.margin, y - rowHeight, page.margin + tableState.tableWidth, y - rowHeight);
        tableState.xs.slice(1, -1).forEach((x) => line(x, y, x, y - rowHeight, "0.88 0.88 0.88", 0.45));

        wrapped.forEach((cellLines, columnIndex) => {
          cellLines.slice(lineOffset, lineOffset + fragmentLines).forEach((cellLine, lineIndex) => {
            text(cellLine, tableState.xs[columnIndex] + 6, y - 13 - lineIndex * 9, 7, COLORS.ink);
          });
        });
        y -= rowHeight;
        lineOffset += fragmentLines;

        if (lineOffset < totalLines) {
          addPage(true);
          drawTableHeader();
        }
      }
    });
  } else {
    ensureSpace(35);
    rect(page.margin, y - 28, page.width - page.margin * 2, 28, COLORS.soft);
    text("No records were available for this report period.", page.margin + 10, y - 18, 8, COLORS.muted);
  }

  const pageCount = pages.length;
  const contents = pages.map((pageCommands) => pageCommands.join("\n").replaceAll("{{PAGE_COUNT}}", String(pageCount)));
  const pageIds = contents.map((_, index) => 3 + index);
  const contentIds = contents.map((_, index) => 3 + pageCount + index);
  const regularFontId = 3 + pageCount * 2;
  const boldFontId = regularFontId + 1;
  const logoImageId = boldFontId + 1;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageCount} >>`,
    ...pageIds.map((_, index) =>
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${page.width} ${page.height}] /Resources << /Font << /F1 ${regularFontId} 0 R /F2 ${boldFontId} 0 R >> /XObject << /Logo ${logoImageId} 0 R >> >> /Contents ${contentIds[index]} 0 R >>`
    ),
    ...contents.map((content) => `<< /Length ${content.length} >>\nstream\n${content}\nendstream`),
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    `<< /Type /XObject /Subtype /Image /Width 420 /Height 420 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter [/ASCIIHexDecode /DCTDecode] /Length ${PAYNIVO_LOGO_HEX.length + 1} >>\nstream\n${PAYNIVO_LOGO_HEX}>\nendstream`
  ];
  const offsets = [0];
  let pdf = "%PDF-1.4\n";

  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return pdf;
}

export function createPayrollReportPdf(options) {
  return new Blob([buildPayrollReportPdf(options)], { type: "application/pdf" });
}
