CREATE DATABASE IF NOT EXISTS paynivo;
USE paynivo;

CREATE TABLE roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status ENUM('Active', 'Inactive') DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE staff_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  staff_id VARCHAR(50) NOT NULL UNIQUE,
  staff_name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(50),
  department VARCHAR(100),
  work_location VARCHAR(150),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payroll_rate_configs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_cpf_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
  employer_cpf_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
  sdl_rate DECIMAL(6,4) NOT NULL DEFAULT 0,
  default_allowance_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
  default_deduction_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE payroll_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  staff_profile_id INT NOT NULL,
  payroll_month VARCHAR(30) NOT NULL,
  working_days DECIMAL(5,2) NOT NULL DEFAULT 0,
  no_pay_leave_days DECIMAL(5,2) NOT NULL DEFAULT 0,
  basic_salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  allowance DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_earnings DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_deductions DECIMAL(12,2) NOT NULL DEFAULT 0,
  employee_cpf DECIMAL(12,2) NOT NULL DEFAULT 0,
  employer_cpf DECIMAL(12,2) NOT NULL DEFAULT 0,
  net_pay DECIMAL(12,2) NOT NULL DEFAULT 0,
  validation_status ENUM('Pending', 'Valid', 'Invalid') DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (staff_profile_id) REFERENCES staff_profiles(id)
);

CREATE TABLE earnings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_record_id INT NOT NULL,
  type VARCHAR(80) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (payroll_record_id) REFERENCES payroll_records(id) ON DELETE CASCADE
);

CREATE TABLE deductions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_record_id INT NOT NULL,
  type VARCHAR(80) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (payroll_record_id) REFERENCES payroll_records(id) ON DELETE CASCADE
);

CREATE TABLE payslips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payroll_record_id INT NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  email_sent_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (payroll_record_id) REFERENCES payroll_records(id)
);

CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL,
  phone VARCHAR(50),
  billing_address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  invoice_number VARCHAR(50) NOT NULL UNIQUE,
  issue_date DATE NOT NULL,
  due_date DATE NOT NULL,
  status ENUM('Draft', 'Sent', 'Viewed', 'Paid', 'Overdue') DEFAULT 'Draft',
  payment_method ENUM('Stripe', 'PayNow', 'Bank transfer') DEFAULT 'Stripe',
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE invoice_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(10,2) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  method ENUM('Stripe', 'PayNow', 'Bank transfer') NOT NULL,
  status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  proof_path VARCHAR(255),
  proof_uploaded_at DATETIME NULL,
  approved_by INT NULL,
  approved_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (invoice_id) REFERENCES invoices(id),
  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE upload_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uploaded_by INT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  total_rows INT DEFAULT 0,
  failed_rows INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE email_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sent_by INT NULL,
  recipient VARCHAR(180) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  email_type VARCHAR(80) NOT NULL,
  status VARCHAR(40) DEFAULT 'Queued',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (sent_by) REFERENCES users(id)
);

CREATE TABLE automation_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  payslip_auto_email_enabled BOOLEAN DEFAULT TRUE,
  payslip_email_day INT DEFAULT 28,
  invoice_auto_email_enabled BOOLEAN DEFAULT TRUE,
  invoice_email_day INT DEFAULT 1,
  reminder_1_days_after_due INT DEFAULT 3,
  reminder_2_days_after_due INT DEFAULT 7,
  whatsapp_enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  actor_email VARCHAR(180),
  action VARCHAR(180) NOT NULL,
  module VARCHAR(80) NOT NULL,
  details TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
