/**
 * PDF Export Service
 *
 * Reusable utility for generating high-quality PDF exports using jsPDF + html2canvas.
 * Handles chart rendering, pagination, page breaks, and consistent styling.
 */

import jsPDF from "jspdf";
import html2canvas from "html2canvas";

// Constants
const PAGE_MARGIN = 20;
const CONTENT_WIDTH_A4 = 210 - PAGE_MARGIN * 2; // mm
const CONTENT_HEIGHT_A4 = 297 - PAGE_MARGIN * 2; // mm
const BRAND_COLOR = [243, 137, 120]; // #F38978
const DARK_COLOR = [37, 30, 31]; // #251E1F
const GRAY_COLOR = [123, 102, 96]; // #7b6660
const LIGHT_BG = [255, 248, 245]; // #fff8f5

/**
 * Capture a DOM element as a high-resolution canvas image.
 * @param {HTMLElement} element - DOM element to capture.
 * @param {Object} options - html2canvas options.
 * @returns {Promise<HTMLCanvasElement>} Rendered canvas.
 */
export async function captureElement(element, options = {}) {
  return html2canvas(element, {
    scale: 2,
    useCORS: true,
    allowTaint: true,
    backgroundColor: "#ffffff",
    logging: false,
    ...options
  });
}

/**
 * Add a cover page to the PDF.
 * @param {jsPDF} doc - jsPDF instance.
 * @param {Object} config - Cover page configuration.
 * @param {string} config.title - Report title.
 * @param {string} config.subtitle - Report subtitle.
 * @param {string} config.generatedBy - User who generated the report.
 * @param {string} config.date - Generation date string.
 */
export function addCoverPage(doc, config) {
  const { title, subtitle, generatedBy, date } = config;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Background
  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Brand accent bar
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, pageWidth, 6, "F");

  // Logo text
  doc.setFontSize(42);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_COLOR);
  doc.text("PayNivo", pageWidth / 2, 80, { align: "center" });

  // Title
  doc.setFontSize(24);
  doc.setTextColor(...DARK_COLOR);
  doc.text(title, pageWidth / 2, 110, { align: "center" });

  // Subtitle
  if (subtitle) {
    doc.setFontSize(14);
    doc.setTextColor(...GRAY_COLOR);
    doc.text(subtitle, pageWidth / 2, 125, { align: "center" });
  }

  // Divider
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 140, pageWidth / 2 + 40, 140);

  // Meta information
  doc.setFontSize(11);
  doc.setTextColor(...GRAY_COLOR);
  doc.text(`Generated: ${date}`, pageWidth / 2, 158, { align: "center" });
  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, pageWidth / 2, 168, { align: "center" });
  }

  // Footer brand
  doc.setFontSize(9);
  doc.setTextColor(...GRAY_COLOR);
  doc.text("Automated Invoice & Payroll System", pageWidth / 2, pageHeight - 20, { align: "center" });
}

/**
 * Add a page footer with page number and branding.
 * @param {jsPDF} doc - jsPDF instance.
 * @param {number} pageNum - Current page number.
 * @param {number} totalPages - Total page count (can be set later).
 * @param {string} timestamp - Generation timestamp.
 */
export function addPageFooter(doc, pageNum, totalPages, timestamp) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer line
  doc.setDrawColor(240, 210, 202);
  doc.setLineWidth(0.3);
  doc.line(PAGE_MARGIN, pageHeight - 15, pageWidth - PAGE_MARGIN, pageHeight - 15);

  // Page number
  doc.setFontSize(8);
  doc.setTextColor(...GRAY_COLOR);
  doc.text(`Page ${pageNum}${totalPages ? ` of ${totalPages}` : ""}`, pageWidth / 2, pageHeight - 10, { align: "center" });

  // Timestamp
  doc.text(timestamp, PAGE_MARGIN, pageHeight - 10);

  // Branding
  doc.text("PayNivo", pageWidth - PAGE_MARGIN, pageHeight - 10, { align: "right" });
}

/**
 * Add a section header to the PDF.
 * @param {jsPDF} doc - jsPDF instance.
 * @param {string} title - Section title.
 * @param {number} y - Y position.
 * @returns {number} New Y position after the header.
 */
export function addSectionHeader(doc, title, y) {
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BRAND_COLOR);
  doc.text(title, PAGE_MARGIN, y);
  doc.setDrawColor(...BRAND_COLOR);
  doc.setLineWidth(0.5);
  doc.line(PAGE_MARGIN, y + 2, PAGE_MARGIN + doc.getTextWidth(title), y + 2);
  return y + 10;
}

/**
 * Add captured chart image to PDF, handling page breaks.
 * @param {jsPDF} doc - jsPDF instance.
 * @param {HTMLCanvasElement} canvas - Captured chart canvas.
 * @param {number} y - Current Y position.
 * @param {number} maxWidth - Max width in mm.
 * @param {number} maxHeight - Max height in mm.
 * @param {Object} pageContext - { pageNum, timestamp } for footer tracking.
 * @returns {number} New Y position after the image.
 */
export function addChartImage(doc, canvas, y, maxWidth, maxHeight, pageContext) {
  const imgData = canvas.toDataURL("image/png");
  const imgRatio = canvas.width / canvas.height;
  let imgWidth = maxWidth || CONTENT_WIDTH_A4;
  let imgHeight = imgWidth / imgRatio;

  if (maxHeight && imgHeight > maxHeight) {
    imgHeight = maxHeight;
    imgWidth = imgHeight * imgRatio;
  }

  // Check if we need a page break
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + imgHeight > pageHeight - 20) {
    addPageFooter(doc, pageContext.pageNum, null, pageContext.timestamp);
    doc.addPage();
    pageContext.pageNum++;
    y = PAGE_MARGIN + 5;
  }

  doc.addImage(imgData, "PNG", PAGE_MARGIN, y, imgWidth, imgHeight);
  return y + imgHeight + 8;
}

/**
 * Add a key-value metric row.
 * @param {jsPDF} doc - jsPDF instance.
 * @param {string} label - Metric label.
 * @param {string} value - Metric value.
 * @param {number} y - Y position.
 * @param {Object} options - Styling options.
 * @returns {number} New Y position.
 */
export function addMetricRow(doc, label, value, y, options = {}) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY_COLOR);
  doc.text(label, PAGE_MARGIN + 4, y);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(...(options.valueColor || DARK_COLOR));
  doc.text(String(value), pageWidth - PAGE_MARGIN - 4, y, { align: "right" });

  return y + 6;
}

/**
 * Create a new jsPDF instance with standard configuration.
 * @param {string} orientation - "portrait" or "landscape".
 * @returns {jsPDF} Configured jsPDF instance.
 */
export function createPdfDocument(orientation = "portrait") {
  return new jsPDF({
    orientation,
    unit: "mm",
    format: "a4"
  });
}

/**
 * Generate and download a PDF with a loading state wrapper.
 * @param {Function} generatorFn - Async function that generates the PDF. Receives no args, returns jsPDF doc.
 * @param {string} fileName - Output file name.
 * @param {Function} onStart - Called when generation starts.
 * @param {Function} onEnd - Called when generation ends (success or failure).
 * @param {Function} onError - Called on error with error message.
 * @param {Function} onSuccess - Called on successful generation.
 */
export async function generateAndDownloadPdf(generatorFn, fileName, { onStart, onEnd, onError, onSuccess } = {}) {
  if (onStart) onStart();
  try {
    const doc = await generatorFn();
    doc.save(fileName);
    if (onSuccess) onSuccess();
  } catch (error) {
    console.error("PDF export failed:", error);
    if (onError) onError(error.message || "PDF export failed. Please try again.");
  } finally {
    if (onEnd) onEnd();
  }
}

// Export constants for external use
export { PAGE_MARGIN, CONTENT_WIDTH_A4, CONTENT_HEIGHT_A4, BRAND_COLOR, DARK_COLOR, GRAY_COLOR };
