/**
 * Invoice Delivery Service
 *
 * Sends invoice emails to customers via Nodemailer.
 * Falls back to console logging if SMTP is not configured.
 */

const nodemailer = require("nodemailer");

/**
 * Create a Nodemailer transporter based on environment configuration.
 * Returns null if SMTP is not configured (demo mode).
 */
function createTransporter() {
  if (!process.env.SMTP_HOST || !process.env.SMTP_USER) {
    return null;
  }

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT || 587),
    secure: Number(process.env.SMTP_PORT) === 465,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });
}

/**
 * Build the HTML email body for an invoice notification.
 *
 * @param {Object} invoice - Invoice data (invoiceId, customer_name, customer_email, total_amount).
 * @returns {string} HTML email body.
 */
function buildInvoiceEmailHtml(invoice) {
  const viewUrl = `${process.env.CLIENT_URL || "http://localhost:5173"}/invoice/view/${invoice.invoiceId}`;
  const amount = Number(invoice.total_amount || 0).toFixed(2);

  return `
    <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #7B2FF7; margin: 0;">PayNivo</h1>
        <p style="color: #666; font-size: 14px;">Invoice Notification</p>
      </div>
      <div style="background: #f8f4ff; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
        <h2 style="color: #1a1a2e; margin: 0 0 8px;">Invoice ${invoice.invoiceId}</h2>
        <p style="color: #666; margin: 4px 0;">Amount: <strong>SGD ${amount}</strong></p>
        <p style="color: #666; margin: 4px 0;">Customer: ${invoice.customer_name}</p>
      </div>
      <p style="color: #333; line-height: 1.6;">
        Dear ${invoice.customer_name},<br><br>
        Your invoice <strong>${invoice.invoiceId}</strong> for <strong>SGD ${amount}</strong> is ready.
      </p>
      <div style="text-align: center; margin: 32px 0;">
        <a href="${viewUrl}" style="display: inline-block; background: #7B2FF7; color: white; padding: 14px 32px; border-radius: 8px; text-decoration: none; font-weight: bold;">
          View & Pay Invoice
        </a>
      </div>
      <p style="color: #999; font-size: 12px; text-align: center;">
        Generated by PayNivo Automated Invoicing System
      </p>
    </div>
  `;
}

/**
 * Send an invoice email to the customer.
 * Uses SMTP if configured, otherwise logs to console (demo mode).
 *
 * @param {Object} invoice - { invoiceId, customer_name, customer_email, total_amount }
 * @returns {Object} Delivery result with provider and timestamp.
 */
async function sendInvoiceEmail(invoice) {
  const transporter = createTransporter();

  if (!transporter) {
    // Demo mode — log to console
    console.log(`[EMAIL] Invoice ${invoice.invoiceId} → ${invoice.customer_email} (${invoice.customer_name}) | SGD ${invoice.total_amount}`);
    return {
      provider: "console",
      deliveredAt: new Date().toISOString(),
      message: "SMTP not configured. Email logged to console."
    };
  }

  // Real email delivery
  const info = await transporter.sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to: invoice.customer_email,
    subject: `Invoice ${invoice.invoiceId} from PayNivo - SGD ${Number(invoice.total_amount || 0).toFixed(2)}`,
    html: buildInvoiceEmailHtml(invoice)
  });

  console.log(`[EMAIL] Sent invoice ${invoice.invoiceId} to ${invoice.customer_email} | MessageID: ${info.messageId}`);

  return {
    provider: "smtp",
    messageId: info.messageId,
    deliveredAt: new Date().toISOString()
  };
}

module.exports = {
  sendInvoiceEmail
};
