/**
 * Invoice Delivery Service
 *
 * Sends invoice emails to customers via Nodemailer.
 * Includes PDF attachment, QR code, and Pay Now button.
 * Falls back to console logging if SMTP is not configured.
 */

const nodemailer = require("nodemailer");
const { generateQRCode } = require("./qrCodeService");

/**
 * Create a Nodemailer transporter based on environment configuration.
 * Returns null if SMTP is not configured (demo mode).
 */
function createTransporter() {
  if (!process.env.SMTP_HOST || !process.env.SMTP_USER) {
    return null;
  }

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT || 587),
    secure: Number(process.env.SMTP_PORT) === 465,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });
}

/**
 * Build the HTML email body for an invoice notification.
 *
 * @param {Object} invoice - Invoice data.
 * @param {Object} [options] - Additional options.
 * @param {string} [options.paymentUrl] - Stripe payment URL.
 * @param {string} [options.qrCodeCid] - CID for embedded QR code image.
 * @returns {string} HTML email body.
 */
function buildInvoiceEmailHtml(invoice, options = {}) {
  const viewUrl = `${process.env.CLIENT_URL || "http://localhost:5173"}/invoice/view/${invoice.invoiceId}`;
  const amount = Number(invoice.total_amount || 0).toFixed(2);
  const dueDate = invoice.due_date || "N/A";
  const { paymentUrl, qrCodeCid } = options;

  const payNowButton = paymentUrl
    ? `<a href="${paymentUrl}" style="display: inline-block; background: #7B2FF7; color: white; padding: 16px 40px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;">
        Pay Now — SGD ${amount}
      </a>
      <p style="color: #999; font-size: 11px; margin-top: 8px;">Secure payment via Stripe • Card, Apple Pay, Google Pay</p>`
    : `<a href="${viewUrl}" style="display: inline-block; background: #7B2FF7; color: white; padding: 16px 40px; border-radius: 8px; text-decoration: none; font-weight: bold; font-size: 16px;">
        View & Pay Invoice
      </a>`;

  const qrSection = qrCodeCid
    ? `<div style="margin-top: 24px; text-align: center;">
        <p style="color: #666; font-size: 13px; margin: 0 0 8px;">Or scan QR code to pay:</p>
        <img src="cid:${qrCodeCid}" alt="Payment QR Code" style="width: 150px; height: 150px;" />
      </div>`
    : "";

  const paymentLinkText = paymentUrl
    ? `<p style="color: #999; font-size: 11px; margin-top: 12px; word-break: break-all;">Direct payment link: <a href="${paymentUrl}" style="color: #7B2FF7;">${paymentUrl}</a></p>`
    : "";

  return `
    <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #7B2FF7; margin: 0;">PayNivo</h1>
        <p style="color: #666; font-size: 14px;">Invoice Notification</p>
      </div>
      <div style="background: #f8f4ff; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
        <h2 style="color: #1a1a2e; margin: 0 0 8px;">Invoice ${invoice.invoiceId}</h2>
        <p style="color: #666; margin: 4px 0;">Amount Due: <strong>SGD ${amount}</strong></p>
        <p style="color: #666; margin: 4px 0;">Due Date: <strong>${dueDate}</strong></p>
        <p style="color: #666; margin: 4px 0;">Customer: ${invoice.customer_name}</p>
      </div>
      <p style="color: #333; line-height: 1.6;">
        Dear ${invoice.customer_name},<br><br>
        Your invoice <strong>${invoice.invoiceId}</strong> for <strong>SGD ${amount}</strong> has been generated.<br><br>
        Please click the Pay Now button or scan the QR Code to complete your payment securely using Stripe.
      </p>
      <div style="text-align: center; margin: 32px 0;">
        ${payNowButton}
        ${paymentLinkText}
      </div>
      ${qrSection}
      <p style="color: #333; line-height: 1.6; margin-top: 24px;">
        Thank you.<br>
        <strong>PayNivo Finance Team</strong>
      </p>
      <p style="color: #999; font-size: 12px; text-align: center; margin-top: 32px;">
        Generated by PayNivo Automated Invoicing System
      </p>
    </div>
  `;
}

/**
 * Send an invoice email to the customer.
 * Includes PDF attachment and QR code when available.
 *
 * @param {Object} invoice - { invoiceId, customer_name, customer_email, total_amount, due_date }
 * @param {Object} [options] - Additional delivery options.
 * @param {Buffer} [options.pdfBuffer] - PDF buffer to attach.
 * @param {string} [options.paymentUrl] - Stripe payment URL.
 * @param {string} [options.qrCodeDataUri] - QR code data URI.
 * @returns {Object} Delivery result with provider and timestamp.
 */
async function sendInvoiceEmail(invoice, options = {}) {
  const transporter = createTransporter();
  const { pdfBuffer, paymentUrl } = options;

  // Generate QR code buffer for CID embedding
  let qrCodeBuffer = null;
  if (options.qrCodeDataUri) {
    const base64Data = options.qrCodeDataUri.split(",")[1];
    if (base64Data) {
      qrCodeBuffer = Buffer.from(base64Data, "base64");
    }
  }

  if (!transporter) {
    // Demo mode — log to console
    console.log(`[EMAIL] Invoice ${invoice.invoiceId} → ${invoice.customer_email} (${invoice.customer_name}) | SGD ${invoice.total_amount}`);
    if (paymentUrl) console.log(`[EMAIL] Payment URL: ${paymentUrl}`);
    if (pdfBuffer) console.log(`[EMAIL] PDF attached (${pdfBuffer.length} bytes)`);
    if (qrCodeBuffer) console.log(`[EMAIL] QR Code attached`);
    return {
      provider: "console",
      deliveredAt: new Date().toISOString(),
      message: "SMTP not configured. Email logged to console."
    };
  }

  // Build attachments
  const attachments = [];
  if (pdfBuffer) {
    attachments.push({
      filename: `${invoice.invoiceId}.pdf`,
      content: pdfBuffer,
      contentType: "application/pdf"
    });
  }

  const qrCodeCid = qrCodeBuffer ? "qrcode@paynivo" : null;
  if (qrCodeBuffer) {
    attachments.push({
      filename: "qrcode.png",
      content: qrCodeBuffer,
      contentType: "image/png",
      cid: qrCodeCid
    });
  }

  // Real email delivery
  const info = await transporter.sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to: invoice.customer_email,
    subject: `Invoice ${invoice.invoiceId} from PayNivo`,
    html: buildInvoiceEmailHtml(invoice, { paymentUrl, qrCodeCid }),
    attachments
  });

  console.log(`[EMAIL] Sent invoice ${invoice.invoiceId} to ${invoice.customer_email} | MessageID: ${info.messageId}`);

  return {
    provider: "smtp",
    messageId: info.messageId,
    deliveredAt: new Date().toISOString()
  };
}

/**
 * Send a payment receipt email to the customer after successful payment.
 *
 * @param {Object} invoice - { invoiceId, customer_name, customer_email, total_amount }
 * @param {string} transactionId - Stripe transaction/payment intent ID.
 * @returns {Object} Delivery result.
 */
async function sendPaymentReceiptEmail(invoice, transactionId) {
  const transporter = createTransporter();
  const amount = Number(invoice.total_amount || 0).toFixed(2);

  const html = `
    <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #7B2FF7; margin: 0;">PayNivo</h1>
        <p style="color: #666; font-size: 14px;">Payment Receipt</p>
      </div>
      <div style="background: #ecfdf5; border-radius: 12px; padding: 24px; margin-bottom: 24px; border: 1px solid #a7f3d0;">
        <h2 style="color: #065f46; margin: 0 0 8px;">✅ Payment Successful</h2>
        <p style="color: #333; margin: 4px 0;">Invoice: <strong>${invoice.invoiceId}</strong></p>
        <p style="color: #333; margin: 4px 0;">Amount Paid: <strong>SGD ${amount}</strong></p>
        <p style="color: #333; margin: 4px 0;">Transaction ID: <strong>${transactionId}</strong></p>
        <p style="color: #333; margin: 4px 0;">Date: <strong>${new Date().toLocaleDateString("en-SG")}</strong></p>
      </div>
      <p style="color: #333; line-height: 1.6;">
        Dear ${invoice.customer_name},<br><br>
        We have received your payment of <strong>SGD ${amount}</strong> for invoice <strong>${invoice.invoiceId}</strong>.
        This email serves as your payment receipt.<br><br>
        Thank you for your prompt payment.<br>
        <strong>PayNivo Finance Team</strong>
      </p>
      <p style="color: #999; font-size: 12px; text-align: center; margin-top: 32px;">
        Generated by PayNivo Automated Invoicing System
      </p>
    </div>
  `;

  if (!transporter) {
    console.log(`[EMAIL] Payment receipt for ${invoice.invoiceId} → ${invoice.customer_email}`);
    return { provider: "console", deliveredAt: new Date().toISOString() };
  }

  const info = await transporter.sendMail({
    from: process.env.SMTP_FROM || process.env.SMTP_USER,
    to: invoice.customer_email,
    subject: `Payment Receipt - Invoice ${invoice.invoiceId} | PayNivo`,
    html
  });

  console.log(`[EMAIL] Receipt sent for ${invoice.invoiceId} to ${invoice.customer_email}`);
  return { provider: "smtp", messageId: info.messageId, deliveredAt: new Date().toISOString() };
}

module.exports = {
  sendInvoiceEmail,
  sendPaymentReceiptEmail
};
