const { buildPayslipHtml } = require("./payslipPdfService");

describe("PayNivo payslip PDF template", () => {
  test("renders tenant branding and the calculated payroll breakdown", () => {
    const html = buildPayslipHtml({
      employee_name: "Sample Employee",
      employee_code: "EMP-001",
      payroll_month: 7,
      payroll_year: 2026,
      base_salary: 3000,
      gross_salary: 3512,
      total_allowances: 512,
      total_deductions: 708.9,
      employee_cpf: 702.4,
      employer_cpf: 597.04,
      net_salary: 2803.1,
      company_name: "Vaniday",
      company_legal_name: "Vaniday Singapore Pte. Ltd.",
      company_registration_number: "201812345K",
      company_address: "200 Victoria Street, Singapore",
      deduction_breakdown: JSON.stringify({
        employeeCpf: 702.4,
        selfHelpGroups: [{ fund: "MBMF", amount: 6.5 }],
        sdl: 8.78,
        reimbursements: [{ claimId: "CLM-001", label: "Transport reimbursement · CLM-001", amount: 42.5, expenseDate: "2026-07-10", cpfApplicable: false }]
      }),
      claims: [{ claim_id: "CLM-001", claim_type: "Transport", amount: 42.5, expense_date: "2026-07-10" }],
      layout: { layout_name: "Vaniday Default" }
    });

    expect(html).toContain("data:image/png;base64,");
    expect(html).toContain("Vaniday Singapore Pte. Ltd.");
    expect(html).toContain("PS-2026-07-");
    expect(html).toContain("Total earnings");
    expect(html).toContain("Employer CPF contribution");
    expect(html).toContain("Skills Development Levy (SDL)");
    expect(html).toContain("Transport reimbursement · CLM-001");
    expect(html).toContain("Payroll reimbursement audit references");
    expect(html).toContain("CLM-001");
    expect(html).toContain("Employee information");
    expect(html).toContain("Payroll details");
    expect(html).toContain("CONFIDENTIAL");
    expect(html).toContain("generated by PayNivo Payroll System on behalf of Vaniday Singapore Pte. Ltd.");
  });
});
