/**
 * PDF Service
 *
 * Generates PDF documents for invoices.
 * Uses html-pdf-node for rendering HTML to PDF buffers.
 */

const htmlPdf = require("html-pdf-node");

/**
 * Generate a PDF buffer from an invoice object.
 *
 * @param {Object} invoice - Invoice data with items array.
 * @returns {Buffer} PDF file buffer ready for download.
 */
async function generateInvoicePDF(invoice) {
  const html = buildInvoiceHtml(invoice);
  const file = { content: html };
  const options = {
    format: "A4",
    margin: { top: "15mm", right: "15mm", bottom: "15mm", left: "15mm" },
    printBackground: true
  };

  const pdfBuffer = await htmlPdf.generatePdf(file, options);
  return pdfBuffer;
}

/**
 * Build HTML content for the invoice PDF.
 *
 * @param {Object} invoice - Invoice with customer info and items.
 * @returns {string} Full HTML document string.
 */
function buildInvoiceHtml(invoice) {
  const items = invoice.items || [];
  const amount = Number(invoice.total_amount || 0).toFixed(2);

  const itemRows = items.map((item, idx) => `
    <tr>
      <td style="padding: 10px; border-bottom: 1px solid #eee;">${idx + 1}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee;">${item.description || ""}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">${item.quantity || 0}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">$${Number(item.unit_price || 0).toFixed(2)}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right;">$${Number(item.amount || 0).toFixed(2)}</td>
    </tr>
  `).join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; color: #1a1a2e; margin: 0; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 40px; border-bottom: 3px solid #7B2FF7; padding-bottom: 20px; }
    .brand { font-size: 32px; font-weight: 900; color: #7B2FF7; }
    .invoice-meta { text-align: right; }
    .invoice-meta h2 { margin: 0; font-size: 22px; }
    .invoice-meta p { margin: 4px 0; color: #666; font-size: 13px; }
    .details { display: flex; justify-content: space-between; margin-bottom: 30px; }
    .details h3 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #999; margin: 0 0 6px; }
    .details p { margin: 2px 0; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background: #1a1a2e; color: white; padding: 10px; text-align: left; font-size: 12px; text-transform: uppercase; }
    th:nth-child(3), th:nth-child(4), th:nth-child(5) { text-align: right; }
    .total { text-align: right; margin-top: 16px; font-size: 20px; font-weight: 900; }
    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 11px; border-top: 1px solid #eee; padding-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">PayNivo</div>
    <div class="invoice-meta">
      <h2>${invoice.invoiceId || ""}</h2>
      <p>Status: ${invoice.status || "Draft"}</p>
      <p>Issue: ${invoice.issue_date || ""}</p>
      <p>Due: ${invoice.due_date || ""}</p>
    </div>
  </div>
  <div class="details">
    <div>
      <h3>Bill To</h3>
      <p><strong>${invoice.customer_name || ""}</strong></p>
      <p>${invoice.customer_email || ""}</p>
      <p>${invoice.customer_address || ""}</p>
    </div>
    <div>
      <h3>From</h3>
      <p><strong>PayNivo</strong></p>
      <p>Automated Invoicing System</p>
    </div>
  </div>
  <table>
    <thead>
      <tr><th>#</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr>
    </thead>
    <tbody>${itemRows}</tbody>
  </table>
  <div class="total">Total: SGD ${amount}</div>
  <div class="footer">Generated by PayNivo • Automated Invoicing & Payroll System</div>
</body>
</html>`;
}

module.exports = {
  generateInvoicePDF
};
